version: "0.1"
synopsis: detect dead code in haskell projects
description: detect dead code in haskell projects
category: Development
maintainer: Sönke Hahn <soenkehahn@gmail.com>
license: BSD3

github: soenkehahn/dead-code-detection

extra-source-files:
  README.md

ghc-options: -Wall -fno-warn-name-shadowing

dependencies:
  - base == 4.*
  - silently
  - getopt-generics
  - ghc
  - Glob
  - string-conversions
  - graph-wrapper
  - containers
  - uniplate
  - ghc-paths
  - gitrev

executables:
  dead-code-detection:
    main: Main.hs
    source-dirs:
      - src
      - driver

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
      - src
    dependencies:
      - hspec
      - mockery
      - interpolate
      - filepath
      - directory
